<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Swagger\\' => array($vendorDir . '/zircote/swagger-php/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Doctrine\\Deprecations\\' => array($vendorDir . '/doctrine/deprecations/src'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/src'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
    'Darkaonline\\L5Swagger\\' => array($vendorDir . '/darkaonline/l5-swagger/src'),
);
