<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb9a4615d056db12744fffac5dadda072
{
    public static $files = array (
        '0ccdf99b8f62f02c52cba55802e0c2e7' => __DIR__ . '/..' . '/zircote/swagger-php/src/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' =>
        array (
            'Symfony\\Component\\Finder\\' => 25,
            'Swagger\\' => 8,
        ),
        'P' =>
        array (
            'Psr\\Cache\\' => 10,
        ),
        'D' =>
        array (
            'Doctrine\\Deprecations\\' => 22,
            'Doctrine\\Common\\Lexer\\' => 22,
            'Doctrine\\Common\\Annotations\\' => 28,
            'Darkaonline\\L5Swagger\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Finder\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Swagger\\' =>
        array (
            0 => __DIR__ . '/..' . '/zircote/swagger-php/src',
        ),
        'Psr\\Cache\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Doctrine\\Deprecations\\' =>
        array (
            0 => __DIR__ . '/..' . '/doctrine/deprecations/src',
        ),
        'Doctrine\\Common\\Lexer\\' =>
        array (
            0 => __DIR__ . '/..' . '/doctrine/lexer/src',
        ),
        'Doctrine\\Common\\Annotations\\' =>
        array (
            0 => __DIR__ . '/..' . '/doctrine/annotations/lib/Doctrine/Common/Annotations',
        ),
        'Darkaonline\\L5Swagger\\' =>
        array (
            0 => __DIR__ . '/..' . '/darkaonline/l5-swagger/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb9a4615d056db12744fffac5dadda072::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb9a4615d056db12744fffac5dadda072::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb9a4615d056db12744fffac5dadda072::$classMap;

        }, null, ClassLoader::class);
    }
}
